-- ============================================================
-- Category-level sales summary for Power BI product page
--
-- Columns:
--   category        -> product category (English name)
-- total_items_sold -> number of product units sold in that category
--                        (counts each item line, not distinct orders —
--                        if an order contains 2 items from the same 
--                        category, both are counted)
--   total_revenue   -> total revenue generated by that category
-- ============================================================

SELECT 
    pt.product_category_name_english AS category,
    COUNT(*) AS total_items_sold,
    SUM(oi.price) AS total_revenue
FROM order_items oi
JOIN orders o ON oi.order_id = o.order_id
JOIN products p ON oi.product_id = p.product_id
JOIN product_category_translation pt ON p.product_category_name = pt.product_category_name
WHERE o.order_status = 'delivered'
GROUP BY pt.product_category_name_english
ORDER BY total_revenue DESC;
